//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales.Resources
{
    using System;


    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource()
        {
        }

        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sales.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Acept.
        /// </summary>
        internal static string Acept
        {
            get
            {
                return ResourceManager.GetString("Acept", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error
        {
            get
            {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No internet conecction.
        /// </summary>
        internal static string NoInthernet
        {
            get
            {
                return ResourceManager.GetString("NoInthernet", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Please turn on  your Internet.
        /// </summary>
        internal static string TurnOnInterner
        {
            get
            {
                return ResourceManager.GetString("TurnOnInterner", resourceCulture);
            }

        }

        internal static string Products
        {
            get
            {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }

        internal static string Description
        {
            get
            {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        internal static string DescripcionPlaceHolder
        {
            get
            {
                return ResourceManager.GetString("DescripcionPlaceHolder", resourceCulture);
            }
        }


        internal static string AddProduct
        {
            get
            {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }


        }



                 internal static string Price
        {
            get
            {
                return ResourceManager.GetString("Price", resourceCulture);
            }


        }

        internal static string PricePlaceHolder
        {
            get
            {
                return ResourceManager.GetString("PricePlaceHolder", resourceCulture);
            }


        }



        internal static string Remarks
               {
            get
            {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }


        }


        internal static string Save
        {
            get
            {
                return ResourceManager.GetString("Save", resourceCulture);
            }


        }


        internal static string ChangueImage
        {
            get
            {
                return ResourceManager.GetString("ChangueImage", resourceCulture);
            }

        }


        internal static string PriceError
        {
            get
            {
                return ResourceManager.GetString("PriceError", resourceCulture);
            }

        }



        internal static string DescriptionError
        {
            get
            {
                return ResourceManager.GetString("DescriptionError", resourceCulture);
            }

        }


        /**/
        internal static string Cancel
        {
            get
            {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }

        }
        /*
        internal static string ChangueImage
        {
            get
            {
                return ResourceManager.GetString("ChangueImage", resourceCulture);
            }

        }*/

        internal static string FromGallery
        {
            get
            {
                return ResourceManager.GetString("FromGallery", resourceCulture);
            }

        }

        internal static string ImagePath
        {
            get
            {
                return ResourceManager.GetString("ImagePath", resourceCulture);
            }

        }

        internal static string ImageSource
        {
            get
            {
                return ResourceManager.GetString("ImageSource", resourceCulture);
            }

        }

        internal static string NewPicture
        {
            get
            {
                return ResourceManager.GetString("NewPicture", resourceCulture);
            }

        }

        internal static string Yes
        {
            get
            {
                return ResourceManager.GetString("Yes", resourceCulture);
            }

        }


        internal static string No
        {
            get
            {
                return ResourceManager.GetString("No", resourceCulture);
            }

        }

        internal static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }

        }



        internal static string DeleteConfirmation
        {
            get
            {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }

        }

        internal static string Edit
        {
            get
            {

              return ResourceManager.GetString("Edit", resourceCulture);
               // return "Edicion";
            }

        }



        

                internal static string Confirmation
        {
            get
            {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }

        }



        internal static string EditProduct
        {
            get
            {

                return ResourceManager.GetString("EditProduct", resourceCulture);
                // return "Edicion";
            }

        }

        public static string Search
        {
            get
            {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }

        public static string Login
        {
            get
            {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }

        public static string EMail
        {
            get
            {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }

        public static string EmailPlaceHolder
        {
            get
            {
                return ResourceManager.GetString("EmailPlaceHolder", resourceCulture);
            }
        }

        public static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        public static string PasswordPlaceHolder
        {
            get
            {
                return ResourceManager.GetString("PasswordPlaceHolder", resourceCulture);
            }
        }

        public static string Rememberme
        {
            get
            {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }

        public static string Forgot
        {
            get
            {
                return ResourceManager.GetString("Forgot", resourceCulture);
            }
        }

        public static string Register
        {
            get
            {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }

        public static string EmailValidation
        {
            get
            {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }

        public static string PasswordValidation
        {
            get
            {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }

        public static string SomethingWrong
        {
            get
            {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }

        public static string Menu
        {
            get
            {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }

        public static string About
        {
            get
            {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }

        public static string Setup
        {
            get
            {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }

        public static string Exit
        {
            get
            {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }

        public static string NoProductsMessage
        {
            get
            {
                return ResourceManager.GetString("NoProductsMessage", resourceCulture);
            }
        }

        public static string FirstName
        {
            get
            {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }

        public static string LastName
        {
            get
            {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }

        public static string Phone
        {
            get
            {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }

        public static string Address
        {
            get
            {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }

        public static string FirstNamePlaceholder
        {
            get
            {
                return ResourceManager.GetString("FirstNamePlaceholder", resourceCulture);
            }
        }

        public static string LastNamePlaceholder
        {
            get
            {
                return ResourceManager.GetString("LastNamePlaceholder", resourceCulture);
            }
        }

        public static string PhonePlaceHolder
        {
            get
            {
                return ResourceManager.GetString("PhonePlaceHolder", resourceCulture);
            }
        }

        public static string AddressPlaceHolder
        {
            get
            {
                return ResourceManager.GetString("AddressPlaceHolder", resourceCulture);
            }
        }

        public static string PasswordConfirm
        {
            get
            {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }

        public static string PasswordConfirmPlaceHolder
        {
            get
            {
                return ResourceManager.GetString("PasswordConfirmPlaceHolder", resourceCulture);
            }
        }

        public static string FirstNameError
        {
            get
            {
                return ResourceManager.GetString("FirstNameError", resourceCulture);
            }
        }

        public static string LastNameError
        {
            get
            {
                return ResourceManager.GetString("LastNameError", resourceCulture);
            }
        }

        public static string EMailError
        {
            get
            {
                return ResourceManager.GetString("EMailError", resourceCulture);
            }
        }

        public static string PhoneError
        {
            get
            {
                return ResourceManager.GetString("PhoneError", resourceCulture);
            }
        }

        public static string PasswordError
        {
            get
            {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }

        public static string PasswordConfirmError
        {
            get
            {
                return ResourceManager.GetString("PasswordConfirmError", resourceCulture);
            }
        }

        public static string PasswordsNoMatch
        {
            get
            {
                return ResourceManager.GetString("PasswordsNoMatch", resourceCulture);
            }
        }

        public static string RegisterConfirmation
        {
            get
            {
                return ResourceManager.GetString("RegisterConfirmation", resourceCulture);
            }
        }

        public static string Categories
        {
            get
            {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }

        public static string Category
        {
            get
            {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }

        public static string CategoryPlaceholder
        {
            get
            {
                return ResourceManager.GetString("CategoryPlaceholder", resourceCulture);
            }
        }

        public static string CategoryError
        {
            get
            {
                return ResourceManager.GetString("CategoryError", resourceCulture);
            }
        }

    }
}
